name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout
      uses: actions/checkout@v4

    - name: Set RUSTFLAGS
      run: echo "RUSTFLAGS='-L/libs'" >> $GITHUB_ENV

    - name: Install deps
      run: cargo install diesel_cli

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
