name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-L./'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout
      uses: actions/checkout@v4

    - name: Install deps
      run: cargo install diesel_cli

    - name: get sqlite3
      run: wget https://github.com/leadedspunk/rustycoins/raw/main/libs/sqlite3.lib

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
