name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-L./libs'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout
      uses: actions/checkout@v4

    - name: Install deps
      run: cargo install diesel_cli #; rustup target add x86_64-pc-windows-msvc

    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu #; cargo build --release --target x86_64-pc-windows-msvc

    # - name: Create Release
    #   id: create_release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: target/release/my_binary

    - name: check files
      run: cd ./target/release; ls -la

    - name: Run tests
      run: cargo test --verbose
